const products = [
  {
    id: '_0001',
    name: 'Product 1',
    price: 69.99,
    description: 'Product 1 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },
  {
    id: '_0002',
    name: 'Product 2',
    price: 69.99,
    description: 'Product 2 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },
  {
    id: '_0003',
    name: 'Product 3',
    price: 69.99,
    description: 'Product 3 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },
  {
    id: '_0004',
    name: 'Product 4',
    price: 69.99,
    description: 'Product 4 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },{
    id: '_0005',
    name: 'Product 5',
    price: 69.99,
    description: 'Product 5 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },{
    id: '_0006',
    name: 'Product 6',
    price: 69.99,
    description: 'Product 6 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },{
    id: '_0007',
    name: 'Product 7',
    price: 69.99,
    description: 'Product 7 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },{
    id: '_0008',
    name: 'Product 8',
    price: 69.99,
    description: 'Product 8 description',
    photo: 'img',
    newProduct: false,
    discount: false,
    lastItem: true,
  },
];